name: CI Lenia

on:
  push:
    branches-ignore:
      - feature/ignore/**
  pull_request:
    branches-ignore:
      - feature/ignore/**

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  generate_doc:
    if: ${{ github.event_name == 'push' && github.ref != 'refs/heads/main' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: build
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: generate documentation
      run: cargo doc --no-deps --target-dir docs
    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "[DOCS] doxygen => generate doxygen mans"
        create_branch: false
